### ISSUE TITLE
Mail Bounce protocol

### ISSUE THREAD

**Issue by rcrath** [digiah/memberconnect#46]
In the current system, if an email bounces (e.g. if someone graduates and their UH address expires), I know to remove the member from the spreadsheet.  What would that functionality look like in MC?  It would be great if it could periodically or automatically trim the database based on bounces.  We would need to be careful that we only cut address "Address not found" bounces, not temp ones, and there would need to be a human approval to avoid, for example, deleting the whole database because the network connection got wonky and bounced everything. 

How would the admin interaction go?  Keep in mind we are hoping to have broader use of the email functions than just admins, but admins are the only ones allowed to delete entries other than one's own.

**Comment by damg70** [comment]
assuming we use the DAHI return address, bounces should go to that account.

so minimally, manually checking that addy would let admin know if an address expired, bounced or was requesting an unsubscribe.

outside of that, we’d have to write some code to look specifically at the server’s mail logs on a chron job.

can you explain the fuller scope of how you imagine email to be used in the context of memberconnect? it sounds like you are imagining a webmail application.

**Comment by rcrath** [comment]
- Our usual missives
- 1 to 1 communication
- filtered interest contact, 1 to many

No need for reader, just send, so not webmail client. 

Option to send self on all emails. Default to yes or not an option. 

All bounces go to uhdahi so we can trim. 

No need for unsubscribe if member can just delete their record

**Comment by damg70** [comment]
having had experience writing mailers for commercial clients we should measure twice and cut once here.

the main risk rolling your own mail system is handling spam or being classified as spam. 

because different clients levels of aggression are unpredictable, messages can vanish.

there is a solution we might explore that allows us to dynamically build “mailto:” HTML links with dynamically-generated subject lines and email bodies. user clicks the link and it launches their mail client, ready to rock.

this way all responsibility is on user.

we might explore this option first.

**Comment by rcrath** [comment]
Agree as per discussion. I will close this and open a new issue with the feature spec we discussed today.
